data_path: ./   # 数据存放路径

# 匹配
registration_method: NDT   # 选择点云匹配方法，目前支持：ICP, NDT, ICP_SVD, ICP_GN

# 局部地图
key_frame_distance: 2.0 # 关键帧距离
local_frame_num: 20
local_map_filter: voxel_filter # 选择滑窗地图点云滤波方法，目前支持：voxel_filter

# rviz显示
display_filter: voxel_filter # rviz 实时显示点云时滤波方法，目前支持：voxel_filter

# 当前帧
frame_filter: voxel_filter # 选择当前帧点云滤波方法，目前支持：voxel_filter

# 各配置选项对应参数
## 匹配相关参数
ICP:
    max_corr_dist : 1.2
    trans_eps : 0.01
    euc_fitness_eps : 0.01
    max_iter : 30
NDT:
    res : 1.6
    step_size : 0.16
    trans_eps : 0.02
    max_iter : 30
ICP_SVD:
    max_corr_dist : 1.2
    trans_eps : 0.01
    euc_fitness_eps : 0.01
    max_iter : 10
ICP_GN:
    max_correspond_dis : 2
    max_iter : 30
## 滤波相关参数
voxel_filter:
    local_map:
        leaf_size: [0.1, 0.1, 0.1]
    frame:
        leaf_size: [0.2, 0.2, 0.2]
    display:
        leaf_size: [0.2, 0.2, 0.2]
